services:
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Jakarta
    volumes:
      - ../files/db_data:/var/lib/mysql
    networks:
      - dokploy-network
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max_allowed_packet=256M

  backend:
    build:
      context: ./attendance-app-webapi
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXP_TIME: ${JWT_EXP_TIME}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SENDER_EMAIL: ${SMTP_SENDER_EMAIL}
      SMTP_SENDER_NAME: ${SMTP_SENDER_NAME}
      GIN_MODE: release
      TZ: Asia/Jakarta
    volumes:
      - ../files/uploads_data:/app/uploads
    networks:
      - dokploy-network
    ports:
      - "8080"
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.attendapp-api.rule=Host(`attendapp.riyaldi.qzz.io`) && PathPrefix(`/api`, `/uploads`, `/swagger`)"
      - "traefik.http.routers.attendapp-api.entrypoints=websecure"
      - "traefik.http.routers.attendapp-api.tls.certResolver=letsencrypt"
      - "traefik.http.services.attendapp-api.loadbalancer.server.port=8080"

  frontend:
    build:
      context: ./attendance-app-frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: /api
    restart: unless-stopped
    networks:
      - dokploy-network
    ports:
      - "80"
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.attendapp-frontend.rule=Host(`attendapp.riyaldi.qzz.io`)"
      - "traefik.http.routers.attendapp-frontend.entrypoints=websecure"
      - "traefik.http.routers.attendapp-frontend.tls.certResolver=letsencrypt"
      - "traefik.http.services.attendapp-frontend.loadbalancer.server.port=80"

networks:
  dokploy-network:
    external: true
